#ifndef BYTECODE_OPCODE_H
#define BYTECODE_OPCODE_H

enum bytecode_opcode
{
    BYTECODE_OPCODE_HALT               = 0x00,

    BYTECODE_OPCODE_MOV_INT8_REG_IMM   = 0x01,
    BYTECODE_OPCODE_MOV_INT16_REG_IMM  = 0x02,
    BYTECODE_OPCODE_MOV_INT32_REG_IMM  = 0x03,
    BYTECODE_OPCODE_MOV_INT64_REG_IMM  = 0x04,
    BYTECODE_OPCODE_MOV_FLT32_REG_IMM  = 0x05,
    BYTECODE_OPCODE_MOV_FLT64_REG_IMM  = 0x06,
    BYTECODE_OPCODE_MOV_REG_REG        = 0x07,
    BYTECODE_OPCODE_MOV_INT8_LCL_IMM   = 0x08,
    BYTECODE_OPCODE_MOV_INT16_LCL_IMM  = 0x09,
    BYTECODE_OPCODE_MOV_INT32_LCL_IMM  = 0x0A,
    BYTECODE_OPCODE_MOV_INT64_LCL_IMM  = 0x0B,
    BYTECODE_OPCODE_MOV_FLT32_LCL_IMM  = 0x0C,
    BYTECODE_OPCODE_MOV_FLT64_LCL_IMM  = 0x0D,
    BYTECODE_OPCODE_MOV_LCL_REG        = 0x0E,
    BYTECODE_OPCODE_MOV_INT8_REG_LCL   = 0x0F,
    BYTECODE_OPCODE_MOV_INT16_REG_LCL  = 0x10,
    BYTECODE_OPCODE_MOV_INT32_REG_LCL  = 0x11,
    BYTECODE_OPCODE_MOV_INT64_REG_LCL  = 0x12,
    BYTECODE_OPCODE_MOV_FLT32_REG_LCL  = 0x13,
    BYTECODE_OPCODE_MOV_FLT64_REG_LCL  = 0x14,

    BYTECODE_OPCODE_PUSH_INT8_IMM      = 0x15,
    BYTECODE_OPCODE_PUSH_INT16_IMM     = 0x16,
    BYTECODE_OPCODE_PUSH_INT32_IMM     = 0x17,
    BYTECODE_OPCODE_PUSH_INT64_IMM     = 0x18,
    BYTECODE_OPCODE_PUSH_FLT32_IMM     = 0x19,
    BYTECODE_OPCODE_PUSH_FLT64_IMM     = 0x1A,
    BYTECODE_OPCODE_PUSH_REG           = 0x1B,

    BYTECODE_OPCODE_POP_REG            = 0x99,
    BYTECODE_OPCODE_POP_INT8_REG       = 0x1C,
    BYTECODE_OPCODE_POP_INT16_REG      = 0x1D,
    BYTECODE_OPCODE_POP_INT32_REG      = 0x1E,
    BYTECODE_OPCODE_POP_INT64_REG      = 0x1F,
    BYTECODE_OPCODE_POP_FLT32_REG      = 0x20,
    BYTECODE_OPCODE_POP_FLT64_REG      = 0x21,

    BYTECODE_OPCODE_ADD_INT8_REG_IMM   = 0x22,
    BYTECODE_OPCODE_ADD_INT16_REG_IMM  = 0x23,
    BYTECODE_OPCODE_ADD_INT32_REG_IMM  = 0x24,
    BYTECODE_OPCODE_ADD_INT64_REG_IMM  = 0x25,
    BYTECODE_OPCODE_ADD_FLT32_REG_IMM  = 0x26,
    BYTECODE_OPCODE_ADD_FLT64_REG_IMM  = 0x27,
    BYTECODE_OPCODE_ADD_REG_REG        = 0x28,

    BYTECODE_OPCODE_SUB_INT8_REG_IMM   = 0x29,
    BYTECODE_OPCODE_SUB_INT16_REG_IMM  = 0x2A,
    BYTECODE_OPCODE_SUB_INT32_REG_IMM  = 0x2B,
    BYTECODE_OPCODE_SUB_INT64_REG_IMM  = 0x2C,
    BYTECODE_OPCODE_SUB_FLT32_REG_IMM  = 0x2D,
    BYTECODE_OPCODE_SUB_FLT64_REG_IMM  = 0x2E,
    BYTECODE_OPCODE_SUB_REG_REG        = 0x2F,

    BYTECODE_OPCODE_MUL_INT8_REG_IMM   = 0x30,
    BYTECODE_OPCODE_MUL_INT16_REG_IMM  = 0x31,
    BYTECODE_OPCODE_MUL_INT32_REG_IMM  = 0x32,
    BYTECODE_OPCODE_MUL_INT64_REG_IMM  = 0x33,
    BYTECODE_OPCODE_MUL_FLT32_REG_IMM  = 0x34,
    BYTECODE_OPCODE_MUL_FLT64_REG_IMM  = 0x35,
    BYTECODE_OPCODE_MUL_REG_REG        = 0x36,

    BYTECODE_OPCODE_DIV_INT8_REG_IMM   = 0x37,
    BYTECODE_OPCODE_DIV_INT16_REG_IMM  = 0x38,
    BYTECODE_OPCODE_DIV_INT32_REG_IMM  = 0x39,
    BYTECODE_OPCODE_DIV_INT64_REG_IMM  = 0x3A,
    BYTECODE_OPCODE_DIV_FLT32_REG_IMM  = 0x3B,
    BYTECODE_OPCODE_DIV_FLT64_REG_IMM  = 0x3C,
    BYTECODE_OPCODE_DIV_REG_REG        = 0x3D,

    BYTECODE_OPCODE_NOT_REG            = 0x3E,
    BYTECODE_OPCODE_LOG_NOT_REG        = 0x3F,
    BYTECODE_OPCODE_NEG_REG            = 0x40,
    BYTECODE_OPCODE_INC_REG            = 0x41,
    BYTECODE_OPCODE_DEC_REG            = 0x42,
    BYTECODE_OPCODE_XOR_REG_REG        = 0x43,
    BYTECODE_OPCODE_OR_REG_REG         = 0x4F,
    BYTECODE_OPCODE_AND_REG_REG        = 0x53,
    BYTECODE_OPCODE_LSHIFT_REG_REG     = 0x54,
    BYTECODE_OPCODE_RSHIFT_REG_REG     = 0x55,

    BYTECODE_OPCODE_TEST_REG_IMM       = 0x44,
    BYTECODE_OPCODE_TEST_REG_REG       = 0x45,
    BYTECODE_OPCODE_CMP_REG_IMM        = 0x46,
    BYTECODE_OPCODE_CMP_REG_REG        = 0x47,
    BYTECODE_OPCODE_JMP_IMM            = 0x48,
    BYTECODE_OPCODE_JNZ_IMM            = 0x49,
    BYTECODE_OPCODE_JZ_IMM             = 0x4A,
    BYTECODE_OPCODE_JLE_IMM            = 0x4B,
    BYTECODE_OPCODE_JL_IMM             = 0x4C,
    BYTECODE_OPCODE_JGE_IMM            = 0x4D,
    BYTECODE_OPCODE_JG_IMM             = 0x4E,

    BYTECODE_OPCODE_CALL_IMM           = 0x50,
    BYTECODE_OPCODE_CALL_REG           = 0x51,
    BYTECODE_OPCODE_CALL_FOREIGN       = 0x52,

    BYTECODE_OPCODE_BEGIN_CALL_FRAME   = 0x60,
    BYTECODE_OPCODE_END_CALL_FRAME     = 0x61,
    BYTECODE_OPCODE_RETURN             = 0x62,

    BYTECODE_OPCODE_LEA_LCL_REG_IMM    = 0x70,
    BYTECODE_OPCODE_LEA_LCL_REG_REG    = 0x71,
    BYTECODE_OPCODE_LEA_BSS_REG_IMM    = 0x72,
    BYTECODE_OPCODE_LEA_BSS_REG_REG    = 0x73,

    BYTECODE_OPCODE_MEMW_INT8_REG_IMM  = 0x80,
    BYTECODE_OPCODE_MEMW_INT16_REG_IMM = 0x81,
    BYTECODE_OPCODE_MEMW_INT32_REG_IMM = 0x82,
    BYTECODE_OPCODE_MEMW_INT64_REG_IMM = 0x83,
    BYTECODE_OPCODE_MEMW_FLT32_REG_IMM = 0x84,
    BYTECODE_OPCODE_MEMW_FLT64_REG_IMM = 0x85,
    BYTECODE_OPCODE_MEMW_REG_REG       = 0x86,

    BYTECODE_OPCODE_MEMR_INT8_REG_REG  = 0x87,
    BYTECODE_OPCODE_MEMR_INT16_REG_REG = 0x88,
    BYTECODE_OPCODE_MEMR_INT32_REG_REG = 0x89,
    BYTECODE_OPCODE_MEMR_INT64_REG_REG = 0x8A,
    BYTECODE_OPCODE_MEMR_FLT32_REG_REG = 0x8B,
    BYTECODE_OPCODE_MEMR_FLT64_REG_REG = 0x8C,

    BYTECODE_OPCODE_MEMC_REG_REG_IMM   = 0x8D,

    BYTECODE_OPCODE_CONV_INT8_REG      = 0x90,
    BYTECODE_OPCODE_CONV_INT16_REG     = 0x91,
    BYTECODE_OPCODE_CONV_INT32_REG     = 0x92,
    BYTECODE_OPCODE_CONV_INT64_REG     = 0x93,
    BYTECODE_OPCODE_CONV_FLT32_REG     = 0x94,
    BYTECODE_OPCODE_CONV_FLT64_REG     = 0x95,

    BYTECODE_OPCODE_NOP                = 0xFF,
    BYTECODE_OPCODE_COUNT              = 0x100
};

static const char *bytecode_opcode_str[BYTECODE_OPCODE_COUNT] =
{
    [0x00] = "halt",

    [0x01] = "mov_int8_reg_imm",
    [0x02] = "mov_int16_reg_imm",
    [0x03] = "mov_int32_reg_imm",
    [0x04] = "mov_int64_reg_imm",
    [0x05] = "mov_flt32_reg_imm",
    [0x06] = "mov_flt64_reg_imm",
    [0x07] = "mov_reg_reg",
    [0x08] = "mov_int8_lcl_imm",
    [0x09] = "mov_int16_lcl_imm",
    [0x0A] = "mov_int32_lcl_imm",
    [0x0B] = "mov_int64_lcl_imm",
    [0x0C] = "mov_flt32_lcl_imm",
    [0x0D] = "mov_flt64_lcl_imm",
    [0x0E] = "mov_lcl_reg",
    [0x0F] = "mov_int8_reg_lcl",
    [0x10] = "mov_int16_reg_lcl",
    [0x11] = "mov_int32_reg_lcl",
    [0x12] = "mov_int64_reg_lcl",
    [0x13] = "mov_flt32_reg_lcl",
    [0x14] = "mov_flt64_reg_lcl",

    [0x15] = "push_int8_imm",
    [0x16] = "push_int16_imm",
    [0x17] = "push_int32_imm",
    [0x18] = "push_int64_imm",
    [0x19] = "push_flt32_imm",
    [0x1A] = "push_flt64_imm",
    [0x1B] = "push_reg",

    [0x99] = "pop_reg",
    [0x1C] = "pop_int8_reg",
    [0x1D] = "pop_int16_reg",
    [0x1E] = "pop_int32_reg",
    [0x1F] = "pop_int64_reg",
    [0x20] = "pop_flt32_reg",
    [0x21] = "pop_flt64_reg",

    [0x22] = "add_int8_reg_imm",
    [0x23] = "add_int16_reg_imm",
    [0x24] = "add_int32_reg_imm",
    [0x25] = "add_int64_reg_imm",
    [0x26] = "add_flt32_reg_imm",
    [0x27] = "add_flt64_reg_imm",
    [0x28] = "add_reg_reg",

    [0x29] = "sub_int8_reg_imm",
    [0x2A] = "sub_int16_reg_imm",
    [0x2B] = "sub_int32_reg_imm",
    [0x2C] = "sub_int64_reg_imm",
    [0x2D] = "sub_flt32_reg_imm",
    [0x2E] = "sub_flt64_reg_imm",
    [0x2F] = "sub_reg_reg",

    [0x30] = "mul_int8_reg_imm",
    [0x31] = "mul_int16_reg_imm",
    [0x32] = "mul_int32_reg_imm",
    [0x33] = "mul_int64_reg_imm",
    [0x34] = "mul_flt32_reg_imm",
    [0x35] = "mul_flt64_reg_imm",
    [0x36] = "mul_reg_reg",

    [0x37] = "div_int8_reg_imm",
    [0x38] = "div_int16_reg_imm",
    [0x39] = "div_int32_reg_imm",
    [0x3A] = "div_int64_reg_imm",
    [0x3B] = "div_flt32_reg_imm",
    [0x3C] = "div_flt64_reg_imm",
    [0x3D] = "div_reg_reg",

    [0x3E] = "not_reg",
    [0x3F] = "log_not_reg",
    [0x40] = "neg_reg",
    [0x41] = "inc_reg",
    [0x42] = "dec_reg",
    [0x43] = "xor_reg_reg",
    [0x4F] = "or_reg_reg",
    [0x53] = "and_reg_reg",
    [0x54] = "left_shift",
    [0x55] = "right_shift",

    [0x44] = "test_reg_imm",
    [0x45] = "test_reg_reg",
    [0x46] = "cmp_reg_imm",
    [0x47] = "cmp_reg_reg",
    [0x48] = "jmp_imm",
    [0x49] = "jnz_imm",
    [0x4A] = "jz_imm",
    [0x4B] = "jle_imm",
    [0x4C] = "jl_imm",
    [0x4D] = "jge_imm",
    [0x4E] = "jg_imm",

    [0x50] = "call_imm",
    [0x51] = "call_reg",
    [0x52] = "call_foreign",

    [0x60] = "begin_call_frame",
    [0x61] = "end_call_frame",
    [0x62] = "return",

    [0x70] = "lea_lcl_reg_imm",
    [0x71] = "lea_lcl_reg_reg",
    [0x72] = "lea_bss_reg_imm",
    [0x73] = "lea_bss_reg_reg",

    [0x80] = "memw_int8_reg_imm",
    [0x81] = "memw_int16_reg_imm",
    [0x82] = "memw_int32_reg_imm",
    [0x83] = "memw_int64_reg_imm",
    [0x84] = "memw_flt32_reg_imm",
    [0x85] = "memw_flt64_reg_imm",
    [0x86] = "memw_reg_reg",

    [0x87] = "memr_int8_reg_reg",
    [0x88] = "memr_int16_reg_reg",
    [0x89] = "memr_int32_reg_reg",
    [0x8A] = "memr_int64_reg_reg",
    [0x8B] = "memr_flt32_reg_reg",
    [0x8C] = "memr_flt64_reg_reg",

    [0x8D] = "memc_reg_reg_imm",

    [0x90] = "conv_int8_reg",
    [0x91] = "conv_int16_reg",
    [0x92] = "conv_int32_reg",
    [0x93] = "conv_int64_reg",
    [0x94] = "conv_flt32_reg",
    [0x95] = "conv_flt64_reg",

    [0xFF] = "nop"
};

#endif
